import { useEffect, useState } from "react";
import { getInvoices } from "./services/api";
import CreateInvoice from "./pages/CreateInvoice"; import InvoiceDetails from "./pages/InvoiceDetails"; import Login from "./pages/Login"; import BusinessSettings from "./pages/BusinessSettings"; import ManageData from "./pages/ManageData";
function App() {
 const [authenticated,setAuthenticated]=useState(Boolean(localStorage.getItem("gstToken"))),[page,setPage]=useState("dashboard"),[invoices,setInvoices]=useState([]),[selectedInvoiceId,setSelectedInvoiceId]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const loadInvoices=async()=>{try{setLoading(true);setInvoices(await getInvoices());setError("")}catch{setError("Failed to load invoices")}finally{setLoading(false)}}; useEffect(()=>{if(authenticated)loadInvoices()},[authenticated]);
 if(!authenticated)return <Login onAuthenticated={()=>setAuthenticated(true)}/>; const logout=()=>{localStorage.removeItem("gstToken");setAuthenticated(false)}; const nav=<div style={{display:"flex",gap:10,marginBottom:25}}><button onClick={()=>setPage("dashboard")}>Dashboard</button><button onClick={()=>setPage("create")}>Create Invoice</button><button onClick={()=>setPage("customers")}>Customers</button><button onClick={()=>setPage("products")}>Products</button><button onClick={()=>setPage("settings")}>Business Settings</button><button onClick={logout}>Logout</button></div>;
 if(page==="create")return <div style={s.container}>{nav}<CreateInvoice onBack={()=>{setPage("dashboard");loadInvoices()}}/></div>; if(page==="details")return <div style={s.container}>{nav}<InvoiceDetails invoiceId={selectedInvoiceId} onBack={()=>{setPage("dashboard");loadInvoices()}}/></div>;if(page==="settings")return <div style={s.container}>{nav}<BusinessSettings/></div>;if(page==="customers"||page==="products")return <div style={s.container}>{nav}<ManageData kind={page}/></div>;
 return <div style={s.container}>{nav}<h1>GST Billing</h1><h2>Recent Invoices</h2>{loading&&<p>Loading invoices...</p>}{error&&<p style={{color:"red"}}>{error}</p>}{!loading&&!error&&<table style={s.table}><thead><tr><th style={s.cell}>Invoice</th><th style={s.cell}>Customer</th><th style={s.cell}>Amount</th><th style={s.cell}>Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td style={s.cell}><button onClick={()=>{setSelectedInvoiceId(i.id);setPage("details")}}>{i.invoiceNumber}</button></td><td style={s.cell}>{i.customer?.name}</td><td style={s.cell}>₹{Number(i.grandTotal).toFixed(2)}</td><td style={s.cell}>{i.status}</td></tr>)}</tbody></table>}</div>;
} const s={container:{padding:40,fontFamily:"Arial"},table:{width:"100%",borderCollapse:"collapse"},cell:{border:"1px solid #ddd",padding:12,textAlign:"left"}}; export default App;
